[env:pico]
platform = raspberrypi
board = pico
framework = arduino

; This allows the compiler to find the Servo library automatically
lib_deps = 
    adafruit/Adafruit PWM Servo Driver Library@^3.0.2

; Matches the baud rate in your app.py
monitor_speed = 9600